# Generated by Django 3.0.6 on 2020-07-14 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='MainInfo',
        ),
    ]
