# Generated by Django 3.0.6 on 2020-07-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200714_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maininfo',
            options={'verbose_name': 'Основная информация о компании', 'verbose_name_plural': 'Основная информация о компании'},
        ),
    ]
