# Generated by Django 3.0.6 on 2020-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200725_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер бота')),
                ('purpose', models.CharField(max_length=200, verbose_name='Предназначение')),
                ('url', models.URLField(help_text='https://api.telegram.org/bot<bot_token>', verbose_name='URL')),
                ('chat_id', models.CharField(max_length=20, verbose_name='Caht ID')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
    ]
