# Generated by Django 3.0.6 on 2020-08-19 02:55

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveSmallIntegerField(verbose_name='Номер стола')),
                ('name', models.CharField(max_length=255, verbose_name='Имя фасилитатора')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('avatar', models.ImageField(upload_to=None, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фасилитатор',
                'verbose_name_plural': 'Фасилитаторы',
            },
        ),
        migrations.CreateModel(
            name='ForumParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveSmallIntegerField(verbose_name='Номер стола')),
                ('speaking_time', models.CharField(max_length=255, verbose_name='Время выступления')),
                ('name', models.CharField(max_length=255, verbose_name='Имя участника')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('avatar', models.ImageField(upload_to=None, verbose_name='Фотография')),
                ('presentation', models.FileField(upload_to=None, verbose_name='Презентация')),
            ],
            options={
                'verbose_name': 'Учатсник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='https://undraw.co/', upload_to=None, verbose_name='Картинка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блока')),
                ('description', models.TextField(verbose_name='Описание блока')),
            ],
            options={
                'verbose_name': 'Блок с описанием',
                'verbose_name_plural': 'Блоки с описанием',
            },
        ),
        migrations.CreateModel(
            name='ForumProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.ForumParticipant', verbose_name='Участники')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.Facilitator', verbose_name='Фасилитаторы')),
            ],
            options={
                'verbose_name': 'Программа форума',
                'verbose_name_plural': 'Программа форума',
            },
        ),
        migrations.CreateModel(
            name='ForumInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы форума')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Подзаголовок страницы форума')),
                ('forum_description_title', models.CharField(max_length=255, verbose_name='Заголовок блока с описанием')),
                ('forum_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание премии')),
                ('info_blocks', models.ManyToManyField(to='forum.InfoBlock', verbose_name='Блоки с информацией')),
            ],
            options={
                'verbose_name': 'Информация о форуме 2019',
                'verbose_name_plural': 'Информация о форуме 2019',
            },
        ),
    ]
