# Generated by Django 3.0.6 on 2020-08-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200819_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitator',
            name='company_logo',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Логотип компании'),
        ),
    ]
