# Generated by Django 3.0.6 on 2020-08-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_facilitator_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoblock',
            name='order',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Порядковый номер'),
        ),
    ]
