# Generated by Django 3.0.6 on 2020-08-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_infoblock_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('image', models.ImageField(upload_to=None, verbose_name='Логотип')),
                ('url', models.URLField(verbose_name='Ссылка на сайт')),
            ],
            options={
                'verbose_name': 'Партнер форума',
                'verbose_name_plural': 'Партнеры форума',
            },
        ),
        migrations.AddField(
            model_name='foruminfo',
            name='forum_2020',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Заглушка для форума 2020'),
        ),
    ]
