# Generated by Django 3.0.6 on 2020-08-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200820_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foruminfo',
            options={'verbose_name': 'Информация о форуме', 'verbose_name_plural': 'Информация о форуме'},
        ),
        migrations.AlterField(
            model_name='forumpartner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
