# Generated by Django 3.0.6 on 2020-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20200820_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumNewParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('company', models.CharField(max_length=300, verbose_name='Компания')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Новая заявка на участие в форуме',
                'verbose_name_plural': 'Новые заявки на участие в форуме',
            },
        ),
    ]
