# Generated by Django 3.0.6 on 2020-08-26 17:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_forumnewparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveSmallIntegerField(verbose_name='Номер стола')),
                ('name', models.CharField(max_length=255, verbose_name='Имя фасилитатора')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('company_logo', models.ImageField(null=True, upload_to=None, verbose_name='Логотип компании')),
                ('avatar', models.ImageField(upload_to=None, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фасилитатор',
                'verbose_name_plural': 'Фасилитаторы 2020',
            },
        ),
        migrations.CreateModel(
            name='ForumParticipant2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveSmallIntegerField(verbose_name='Номер стола')),
                ('speaking_time', models.CharField(max_length=255, verbose_name='Время выступления')),
                ('name', models.CharField(max_length=255, verbose_name='Имя участника')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('avatar', models.ImageField(upload_to=None, verbose_name='Фотография')),
                ('presentation', models.FileField(upload_to=None, verbose_name='Презентация')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры 2020',
            },
        ),
        migrations.AlterModelOptions(
            name='facilitator',
            options={'verbose_name': 'Фасилитатор', 'verbose_name_plural': 'Фасилитаторы 2019'},
        ),
        migrations.AlterModelOptions(
            name='forumparticipant',
            options={'verbose_name': 'Спикер', 'verbose_name_plural': 'Спикеры 2019'},
        ),
        migrations.AddField(
            model_name='foruminfo',
            name='forum_2020_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст (заглушка для форума 202)'),
        ),
    ]
