# Generated by Django 3.0.6 on 2020-09-15 04:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20200915_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumparticipant2020',
            name='company',
        ),
        migrations.AddField(
            model_name='facilitator2020',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Био'),
        ),
        migrations.AddField(
            model_name='forumparticipant2020',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Био'),
        ),
        migrations.AddField(
            model_name='forumparticipant2020',
            name='company_logo',
            field=models.ImageField(null=True, upload_to=None, verbose_name='Логотип компании'),
        ),
    ]
