# Generated by Django 3.0.6 on 2020-09-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20200915_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumparticipant',
            name='special_quest',
            field=models.BooleanField(default=False, verbose_name='Специальный гость'),
        ),
    ]
