# Generated by Django 3.0.6 on 2020-09-02 03:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Опыт работы для резюме',
                'verbose_name_plural': 'Опыт работы для резюме',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название профиля')),
            ],
            options={
                'verbose_name': 'Профиль для резюме',
                'verbose_name_plural': 'Профили для резюме',
            },
        ),
        migrations.CreateModel(
            name='SelfRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Запрос')),
            ],
            options={
                'verbose_name': 'Запрос для резюме',
                'verbose_name_plural': 'Запросы для резюме',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None, verbose_name='Картинка услуги')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок - название услуги')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание услуги')),
                ('form', models.BooleanField(default=False, verbose_name='Форма заявки')),
                ('form_resume', models.BooleanField(default=False, verbose_name='Форма с резюме')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сферы')),
            ],
            options={
                'verbose_name': 'Сфера для резюме',
                'verbose_name_plural': 'Сферы для резюме',
            },
        ),
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Дполнительно - услуга',
                'verbose_name_plural': 'Дополнительно - услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceContactResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('resume', models.FileField(upload_to=None, verbose_name='Файл')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Experience', verbose_name='Опыт работы')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Profile', verbose_name='Профиль')),
                ('self_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.SelfRequest', verbose_name='Запрос')),
                ('sphere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Sphere', verbose_name='Сфера')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('comment', models.TextField(verbose_name='Дополнительно')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заявка на услугу',
                'verbose_name_plural': 'Новые заявки на участие',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='sub_service',
            field=models.ManyToManyField(to='service.SubService', verbose_name='Дополнительные услуги'),
        ),
    ]
