# Generated by Django 3.0.6 on 2020-09-02 03:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20200902_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы со списком услуг')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Дополнительная информация на странице со списком услуг')),
            ],
            options={
                'verbose_name': 'Услуги - общая информация',
                'verbose_name_plural': 'Услуги - общая информация',
            },
        ),
        migrations.AlterModelOptions(
            name='subservice',
            options={'verbose_name': 'Дополнительно - услуга', 'verbose_name_plural': 'Дополнительно - услуги'},
        ),
    ]
