# Generated by Django 3.0.6 on 2020-09-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200902_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecontact',
            options={'verbose_name': 'Заявка на услугу', 'verbose_name_plural': 'Заявки на услуги'},
        ),
        migrations.AddField(
            model_name='subservice',
            name='program',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Программа (файл PDF)'),
        ),
    ]
