# Generated by Django 3.0.6 on 2020-09-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200902_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='btn_text',
            field=models.CharField(default='Скачать', max_length=255, verbose_name='Текст на кнопке скачивания программы'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='presentation_text',
            field=models.TextField(default='Ознакомиться с программой', verbose_name='Текст, предлагающий скачать программу или презентацию'),
        ),
    ]
