# Generated by Django 3.0.6 on 2020-09-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200902_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontact',
            name='service',
            field=models.CharField(max_length=255, verbose_name='Услуга'),
        ),
    ]
