# Generated by Django 3.0.6 on 2020-09-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200902_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontact',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Услуга'),
        ),
    ]
