# Generated by Django 3.0.6 on 2020-09-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20200902_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
    ]
