# Generated by Django 3.0.6 on 2020-09-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Картинка на странице услуг'),
        ),
    ]
