# Generated by Django 3.0.6 on 2020-09-02 11:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_serviceinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Дополнительная информация на странице со списком услуг'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок страницы со списком услуг'),
        ),
    ]
