# Generated by Django 3.0.6 on 2020-09-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20200902_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Картинка услуги (необязательно)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Картинка услуги (необязательно)'),
        ),
    ]
