# Generated by Django 3.0.6 on 2020-07-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhrequest',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата подачи заявки'),
        ),
    ]
