# Generated by Django 3.0.6 on 2020-07-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhbase', '0002_hhrequest_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhrequest',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
