# Generated by Django 3.0.6 on 2020-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhbase', '0003_hhrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hhrequest',
            name='resume',
            field=models.FileField(upload_to=None, verbose_name='Резюме'),
        ),
    ]
