# Generated by Django 3.0.6 on 2020-07-14 19:39

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(max_length=200, verbose_name='Блок премия - заголовок')),
                ('award_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Блок премия - описание')),
                ('award_image', models.ImageField(help_text='не забудьте оптимизировать картинку на сайте https://tinypng.com/', upload_to='images/', verbose_name='Блок премия - картинка')),
                ('jury_title', models.CharField(max_length=200, verbose_name='Блок жюри - заголовок')),
                ('jury_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Блок жюри - описание')),
                ('involvement_title', models.CharField(max_length=200, verbose_name='Блок участие - заголовок')),
                ('involvement_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Блок участие - описание')),
            ],
            options={
                'verbose_name': 'Премия общая информация',
                'verbose_name_plural': 'Премия общая информация',
            },
        ),
        migrations.CreateModel(
            name='AwardsIconBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Блок с иконкой - заголовок')),
                ('description', models.TextField(verbose_name='Блок с иконкой - Описание')),
                ('icon', models.CharField(help_text='Скопируйте иконку с сайта https://www.icofont.com/icons', max_length=200, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Блок с иконкой (Премия)',
                'verbose_name_plural': 'Блоки с иконкой (Премия)',
            },
        ),
        migrations.CreateModel(
            name='JuryApproved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Имя жюри')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('recommendation', models.TextField(blank=True, verbose_name='Рекоммендации')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания рекомендации')),
            ],
            options={
                'verbose_name': 'Мнение жюри',
                'verbose_name_plural': 'Мнения жюри',
            },
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название номинации')),
            ],
        ),
        migrations.CreateModel(
            name='NominationJury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название номинации от жюри')),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='ip голосующего')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_date', models.DateTimeField(auto_created=True, verbose_name='Дата внесения правок')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('professional', models.CharField(max_length=100, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('project_name', models.CharField(max_length=300, verbose_name='Название проекта')),
                ('project_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата внедрения проекта')),
                ('resume', models.FileField(upload_to='award_files/', verbose_name='Резюме проекта')),
                ('video', models.URLField(verbose_name='Ссылка на видеопрезентацию')),
                ('presentation', models.FileField(upload_to='award_files', verbose_name='Презентация проекта (форматы pptx/pdf')),
                ('public', models.BooleanField(default=False, verbose_name='Опубликовать')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи заявки')),
                ('to_edit_notification', models.TextField(blank=True, verbose_name='Уведомление для участника')),
                ('approved_by_jury', models.ManyToManyField(to='awards.JuryApproved', verbose_name='Одобрено жюри')),
                ('jurys_nomination', models.ManyToManyField(to='awards.NominationJury', verbose_name='Голос')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='awards.Nomination', verbose_name='Номинация')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.Promocode', verbose_name='Промокод')),
                ('user', models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь на сайте')),
                ('vote', models.ManyToManyField(to='awards.Vote', verbose_name='Голос')),
            ],
            options={
                'verbose_name': 'Заявка на премию',
                'verbose_name_plural': 'Заявки на премию',
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('professional', models.CharField(max_length=200, verbose_name='Профессия')),
                ('interview', models.URLField(verbose_name='Ссылка на интервью')),
                ('preview', models.TextField(max_length=500, verbose_name='Краткая информация (один абзац)')),
                ('avatar', models.ImageField(help_text='не забудьте оптимизировать картинку на сайте https://tinypng.com/', upload_to='images/jury/', verbose_name='Фото (аватар)')),
                ('user', models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь на сайте')),
            ],
            options={
                'verbose_name': 'Член жюри',
                'verbose_name_plural': 'Члены жюри',
            },
        ),
    ]
