# Generated by Django 3.0.6 on 2020-07-20 21:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20200721_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='project_appoints',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Преимущества проекта'),
        ),
    ]
