# Generated by Django 3.0.6 on 2020-07-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_auto_20200721_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='juryapproved',
            name='vote',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='award_files/', verbose_name='Аватар (только для жюри)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='approved_by_jury',
            field=models.ManyToManyField(blank=True, null=True, to='awards.JuryApproved', verbose_name='Одобрено жюри'),
        ),
        migrations.AlterField(
            model_name='request',
            name='jurys_nomination',
            field=models.ManyToManyField(blank=True, null=True, to='awards.NominationJury', verbose_name='Рекомендовать к номинации'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vote',
            field=models.ManyToManyField(blank=True, null=True, to='awards.Vote', verbose_name='Голос'),
        ),
    ]
