# Generated by Django 3.0.6 on 2020-07-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0010_request_for_jury_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='juryapproved',
            name='nomination_jury',
            field=models.ManyToManyField(blank=True, to='awards.NominationJury', verbose_name='Рекомендация к номинации'),
        ),
        migrations.AddField(
            model_name='juryapproved',
            name='project',
            field=models.CharField(blank=True, max_length=200, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='request',
            name='approved_by_jury',
            field=models.ManyToManyField(blank=True, to='awards.JuryApproved', verbose_name='Мнения жюри'),
        ),
        migrations.AlterField(
            model_name='request',
            name='jurys_nomination',
            field=models.ManyToManyField(blank=True, to='awards.NominationJury', verbose_name='Рекомендовать к номинации'),
        ),
        migrations.AlterField(
            model_name='request',
            name='vote',
            field=models.ManyToManyField(blank=True, to='awards.Vote', verbose_name='Голос'),
        ),
    ]
