# Generated by Django 3.0.6 on 2020-07-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0011_auto_20200725_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juryapproved',
            name='project',
        ),
        migrations.RemoveField(
            model_name='request',
            name='approved_by_jury',
        ),
        migrations.AddField(
            model_name='juryapproved',
            name='award_request',
            field=models.ManyToManyField(blank=True, to='awards.Request', verbose_name='Заявка'),
        ),
    ]
