# Generated by Django 3.0.6 on 2020-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0016_juryapproved_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jury',
            name='user',
        ),
        migrations.DeleteModel(
            name='Promocode',
        ),
        migrations.AddField(
            model_name='profile',
            name='interview',
            field=models.URLField(null=True, verbose_name='Ссылка на интервью (только для жюри)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preview',
            field=models.TextField(max_length=500, null=True, verbose_name='Краткая информация - один абзац (только для жюри)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='professional',
            field=models.CharField(max_length=200, null=True, verbose_name='Профессия (только для жюри)'),
        ),
        migrations.DeleteModel(
            name='Jury',
        ),
    ]
