# Generated by Django 3.0.8 on 2020-07-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0019_auto_20200727_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
