# Generated by Django 3.0.6 on 2020-07-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0020_remove_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interview',
            field=models.TextField(null=True, verbose_name='Ссылка на интервью (только для жюри)'),
        ),
    ]
