# Generated by Django 3.0.8 on 2020-07-28 14:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0022_auto_20200727_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название компании - партнера')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на сайт партнера')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.AlterField(
            model_name='awardinfo',
            name='award_image',
            field=models.ImageField(help_text='не забудьте оптимизировать картинку на сайте https://tinypng.com/', upload_to=None, verbose_name='Блок премия - картинка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Аватар (только для жюри)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Краткая информация(только для жюри)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Ваша фотография'),
        ),
        migrations.AlterField(
            model_name='request',
            name='presentation',
            field=models.FileField(upload_to=None, verbose_name='Презентация проекта (форматы pptx/pdf)'),
        ),
        migrations.AlterField(
            model_name='request',
            name='resume',
            field=models.FileField(upload_to=None, verbose_name='Резюме заявителя'),
        ),
        migrations.AlterField(
            model_name='request',
            name='video',
            field=models.TextField(verbose_name='Youtube ролик с видеопрезентацией проекта'),
        ),
    ]
