# Generated by Django 3.0.6 on 2020-07-29 15:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0023_auto_20200728_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardinfo',
            name='votes_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Блок голсование - описание (заголов 3 уровня)'),
        ),
    ]
