# Generated by Django 3.0.6 on 2020-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0024_awardinfo_votes_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardNewParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('company', models.CharField(max_length=300, verbose_name='Компания')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Новая заявка на участие',
                'verbose_name_plural': 'Новые заявки на участие',
            },
        ),
    ]
