# Generated by Django 3.0.6 on 2020-07-30 12:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0025_awardnewparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Блок с иконкой - заголовок')),
                ('description', models.TextField(verbose_name='Блок с иконкой - Описание')),
                ('icon', models.CharField(help_text='Скопируйте иконку с сайта https://www.icofont.com/icons', max_length=200, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Блок с иконкой - Участие (Премия)',
                'verbose_name_plural': 'Блоки с иконкой - Участие (Премия)',
            },
        ),
        migrations.CreateModel(
            name='SecondIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Блок с иконкой - заголовок')),
                ('description', models.TextField(verbose_name='Блок с иконкой - Описание')),
                ('icon', models.CharField(help_text='Скопируйте иконку с сайта https://www.icofont.com/icons', max_length=200, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Блок с иконкой голсование 1 - Участие (Премия)',
                'verbose_name_plural': 'Блоки с иконкой голосование 1 - Участие (Премия)',
            },
        ),
        migrations.CreateModel(
            name='ThreeIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Блок с иконкой - заголовок')),
                ('description', models.TextField(verbose_name='Блок с иконкой - Описание')),
                ('icon', models.CharField(help_text='Скопируйте иконку с сайта https://www.icofont.com/icons', max_length=200, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Блок с иконкой голсование 2 - Участие (Премия)',
                'verbose_name_plural': 'Блоки с иконкой голосование 2 - Участие (Премия)',
            },
        ),
        migrations.AddField(
            model_name='awardinfo',
            name='votes_description_second',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Блок голосование 2 - описание (заголовок 3 уровня)'),
        ),
        migrations.AlterField(
            model_name='awardinfo',
            name='votes_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Блок голосование - описание (заголовок 3 уровня)'),
        ),
    ]
